---
# Default values to be merged into tasks:
auto_cancellation: false
env:
  PATH: /opt/conda/bin:$PATH
  COVERALLS_REPO_TOKEN: zVMEAj6vQZiEmwZOIKtZIcHU3JJOsBsi3
  PIP_CACHE: ${HOME}/.cache/pip
  LC_ALL: C.UTF-8
  LANG: C.UTF-8
  ENV_NAME: justcause
  ENV_PATH: /opt/conda/envs/{ENV_NAME}/
  R_CACHE: ${ENV_PATH}/lib/R/library/
  # CIRRUS_SHELL: /bin/bash


linux_task:
  name: test (Linux - Anaconda)
  # use custom cloning since otherwise git tags are missing
  install_script:
    - apt-get install -y git
  clone_script: |
    if [ -z "$CIRRUS_PR" ]; then
      git clone --recursive --branch=$CIRRUS_BRANCH https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    else
      git clone --recursive https://x-access-token:${CIRRUS_REPO_CLONE_TOKEN}@github.com/${CIRRUS_REPO_FULL_NAME}.git $CIRRUS_WORKING_DIR
      git fetch origin pull/$CIRRUS_PR/head:pull/$CIRRUS_PR
      git reset --hard $CIRRUS_CHANGE_IN_REPO
    fi
  container: {image: "continuumio/anaconda3:latest"}
  pip_cache:
    folder: $PIP_CACHE
  prepare_script:
    - source /opt/conda/etc/profile.d/conda.sh &> /dev/null
    - rm -rf .coverage junit-*.xml
    # ^  avoid information carried from one run to the other
    - conda env create -f environment.yaml -q  # install in root env
    - conda activate $ENV_NAME &> /dev/null
    - python setup.py develop
    - pre-commit install
  r_cache: # deactivate in case of caching errors, only speeds things up
    folder: $R_CACHE
  info_script:
    - conda list -h $ENV_NAME
    - conda config --show
  test_script:
    - source /opt/conda/etc/profile.d/conda.sh &> /dev/null
    - conda activate $ENV_NAME &> /dev/null
    - conda list
    - py.test tests --color yes
    - pre-commit run --all-files
  coverage_script:
    - source /opt/conda/etc/profile.d/conda.sh &> /dev/null
    - conda activate $ENV_NAME &> /dev/null
    - coverage combine .coverage
    - coveralls
