name: justcause
channels:
  - r
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - pandas
  - scikit-learn
  - pip
  - seaborn
  - rpy2
  - seaborn
  - tensorflow
  - keras
  - pymongo
  - pip:
      - sacred