name: justcause
channels:
  - r
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - scipy
  - pandas
  - scikit-learn
  - pip
  - seaborn
  - rpy2
  - seaborn
  - tensorflow
  - keras
  - pymongo
  # for development below here
  - pytest
  - pytest-cov
  - pytest-virtualenv
  - coverage
  - coveralls
  - flake8
  - pre_commmit
  - pip:
      - sacred
